name: Server CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Verify if there's a newer version

      - name: Build Server Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_SERVER }}:latestv1 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 # Verify if there's a newer version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Server Docker Image to Registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_SERVER }}:latestv1 .

      - name: Deploy to Server
        uses: appleboy/ssh-action@master 
        with:
          host: 163.172.194.175
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd pee/
            docker compose pull app
            docker compose up -d app
